### ISSUE TITLE
Add an external configuration file

### ISSUE THREAD

**Issue by machawk1** [N0taN3rd/MementoClientValidator#3]
In your message, you mentioned that it can only be run on a certain port. A couple ways to quickly remedy this is provide an external file to the app, similar to a .ini, that specified options like port:value . You may also want to allow other options at some point, so externalizing the attributes of the service will help with customization, testing, etc.

**Comment by N0taN3rd** [comment]
@machawk1 you have been added as a collaborator and have push access.

Per the externalization of the services attributes they will be moved to a conf file as described in the [options](http://tornadokevinlee.readthedocs.io/en/latest/options.html) documentation. 

As of now, it parses the command line using tornados built in cli parser line 27 and defaults to port 8000 line 11 in mementoClientTestServer.py

**Comment by N0taN3rd** [comment]
As of commit 750d69d39d2eb6ae1e93d9199dab8e8a70c3201c the service can be configured using the server.conf file
